## Почему то с '-standalone' в названии файла не запускается по указанному порту
## Файл не считывается если ввести в названии '-standalone'
server:
   port: 8189
   servlet:
      context-path: /crm
jwt:
   secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
   lifetime: 60m
spring:
   application:
      name: Sewing-atelier-CRM-service
   security:
      user:
         name: service-user
         password: password
         roles:
            - SERVICE
   datasource:
      url: jdbc:postgresql://localhost:5432/Sewing-atelier-CRM-service
      username: postgres
      password: admin
   flyway: 
      schemas: 
         - public
         - catalogue
   jpa:
      show-sql: true
logging:
   level:
      sql: info
