## Файл не считывается если ввести в названии '-standalone'
spring:
   application:
      name: Sewing-atelier-CRM-client
sa:
   service:
      crm:
         uri: http://localhost:8081
         username: service-user
         password: password